/* Banque d'exercices FR + EN → catégorie (11 catégories, ~745 termes). Sert à l'icône
   de chaque ligne enrichie (ExerciseLineView) et aux suggestions de nom de l'éditeur. Termes sans accents,
   en minuscules ; correspondance par mots entiers, pluriels et accents ignorés, le terme le plus long gagne
   ("pallof press" > "press"). Mesuré le 2026-10-07 : catégorie trouvée sur 97 % des lignes tapées. */

export type ExerciseCategory = "halt" | "legs" | "push" | "pull" | "core" | "plio" | "sprint" | "cardio" | "skill" | "test" | "warm";

const BANK: Record<ExerciseCategory, string> = {
  halt: `haltero|halterophilie|technique haltero|seance haltero|weightlifting|snatch|arrache|arrache flexion|arrache debout|power snatch|hang snatch|hang power snatch|muscle snatch|tall snatch|snatch pull|snatch high pull|snatch deadlift|snatch grip|snatch grip deadlift|snatch balance|heaving snatch balance|drop snatch|block snatch|pause snatch|no feet snatch|slow snatch|hip snatch|dip snatch|sots press|overhead squat|ohs|clean|epaule|epaule debout|epaule flexion|epaule jete|power clean|hang clean|hang power clean|squat clean|muscle clean|tall clean|block clean|pause clean|slow clean|no feet clean|clean pull|clean high pull|clean deadlift|slow pull|halting|high pull|panda pull|clean and jerk|clean jerk|clean & jerk|clean&jerk|c&j|cnj|cj|jerk|jete|split jerk|push jerk|power jerk|squat jerk|pause jerk|jerk btn|btn jerk|behind the neck jerk|jerk dip|jerk drive|dip and drive|jerk recovery|push press|sn push press|sn balance|pc|pj|sn|hang|haltero|halterophilie|weightlifting|olympic lift`,
  legs: `squat|back squat|front squat|bs|fs|box squat|pause squat|tempo squat|pin squat|anderson squat|goblet squat|gobelet squat|zercher|zercher squat|safety bar squat|ssb squat|ssb|hack squat|belt squat|leg press|presse|presse a cuisses|presse jambes|pistol|pistol squat|sissy squat|cossack squat|spanish squat|split squat|bulgarian split squat|rear foot elevated split squat|rfess|oh split squat|fente|fentes|fente bulgare|fentes bulgares|fente arriere|fentes arrieres|fente avant|fente marchee|fentes marchees|fente laterale|walking lunge|lunge|lunges|reverse lunge|lateral lunge|curtsy lunge|step up|step|montee sur banc|deadlift|souleve de terre|sdt|souleve de terre roumain|souleve de terre jambes tendues|rdl|romanian deadlift|stiff leg deadlift|sldl|sumo deadlift|conventional deadlift|trap bar deadlift|trap bar|hex bar|single leg deadlift|sl rdl|sprinter rdl|b stance rdl|good morning|hip thrust|glute bridge|pont fessier|pont|single leg glute bridge|kettlebell swing|kb swing|swing|leg extension|leg curl|nordic|nordic curl|nordic hamstring|ischio|ischios|ischio jambiers|hamstring curl|mollet|mollets|calf raise|extension mollets|soleus|adducteur|adducteurs|abducteur|abducteurs|adduction|abduction|hip flexion|hip flex|flexion de hanche|psoas|back extension|back ext|extension lombaire|hyperextension|reverse hyper|ghr|glute ham raise|ankle|cheville|tibialis|tib raise|wall sit|chaise|isometric squat|sled push|prowler|thruster|jambes|quadriceps|quads|fessiers|glutes|air squat|membres inferieurs|renforcement membres inferieurs|roman chair|chaine posterieure|squat clair|dl|sl sprinter dl|flexion dorsale|montee sur pointe|extension de hanche|tenue|chaise`,
  push: `bench|bench press|developpe|developpe couche|dc|developpe incline|incline bench|developpe decline|decline bench|developpe militaire|military press|overhead press|ohp|strict press|shoulder press|developpe epaules|developpe halteres|dumbbell press|db press|floor press|close grip bench|spoto press|larsen press|board press|pompe|pompes|push up|pushup|dips|dip|handstand push up|hspu|pike push up|landmine press|z press|arnold press|elevation laterale|elevations laterales|lateral raise|elevation frontale|front raise|triceps|extension triceps|skull crusher|barre au front|pushdown|triceps pushdown|kickback|ecarte|ecartes|ecarte couche|chest fly|pec fly|pec deck|pectoraux|pecs|epaules|handstand|handstand hold|equilibre sur les mains|pike|atr|atr contre mur|poirier`,
  pull: `traction|tractions|pull up|pullup|chin up|chinup|muscle up|tirage|tirage vertical|tirage horizontal|tirage poitrine|tirage nuque|lat pulldown|pulldown|straight arm pulldown|rowing|row|barbell row|bent over row|pendlay row|rowing barre|rowing haltere|one arm row|dumbbell row|db row|seal row|cable row|seated row|chest supported row|inverted row|australian pull up|ring row|sl row|face pull|oiseau|rear delt|reverse fly|shrug|shrugs|haussement d epaules|curl|curls|biceps|curl biceps|hammer curl|curl marteau|rope climb|montee de corde|pullover|renegade row|dos|dorsaux|lats|banded pull apart|pull apart|tirage epaule|tirage arrache`,
  core: `gainage|gainage lateral|planche|plank|side plank|abs|abdos|abdominaux|crunch|crunchs|sit up|situp|seat up|ghd sit up|ghd situp|bench situp|releve de jambes|leg raise|hanging leg raise|toes to bar|t2b|knees to elbow|hollow|hollow hold|hollow rock|superman|bird dog|dead bug|pallof|pallof press|russian twist|woodchop|bucheron|ab wheel|roulette|rollout|l sit|dragon flag|v up|copenhagen|copenhague|ball pass|farmer walk|farmer|farmers carry|suitcase carry|carry|anti rotation|oblique|obliques|core|oh hold|overhead hold|proprioception|equilibre|unipodal|bipodal|plateau instable|roue abdominale|port de charge|sac leste|position de rappel|hiking`,
  plio: `saut|sauts|sauter|saute|jump|jumps|box jump|saut sur box|saut en contrebas|depth jump|drop jump|drop in|drop to broad jump|broad jump|saut en longueur|triple saut|triple jump|triple broad jump|bound|bounds|bounding|bondissement|bondissements|foulees bondissantes|hop|hops|pogo|pogos|squat jump|split squat jump|split jump|jumping lunge|fente sautee|fentes sautees|switch|switch drill|jump switch|skip|skips|jump skip|haies|saut de haies|sauts de haies|hurdle|hurdle hop|tuck jump|lateral bound|plio|pliometrie|plyo|plyometric|plyometrie|medicine ball|med ball|medecine ball|lancer|throw|slam|ball slam|chest pass|scoop toss|rebond|contrebas|contrehaut|single leg hop|sl hop|sl hops|counter movement jump|cmj|exercice pliometrique|pliometrique|montee de genoux explosive`,
  sprint: `sprint|sprints|acceleration|accelerations|accel|acc|fly|flying|lance|sprint lance|tempo|tempo run|depart|departs|start|starts|kneeling start|block start|starting blocks|three point start|3 point start|build up|montee en vitesse|cote|en cote|hill sprint|sled sprint|resisted sprint|traineau|contraste|a skip|b skip|gammes|gamme|drill|drills|wicket|wickets|navette|navettes|shuttle|shuttle run|changement de direction|change de direction|cod|agility|agilite|echelle|ladder|max speed|vitesse max|vitesse|speed|changement de direction|montee de genoux|talons fesses|foulee|ligne droite|5 10 5|pro agility`,
  cardio: `course|course a pied|footing|jogging|run|running|endurance|endurance fondamentale|ef|fractionne|interval|intervals|seuil|threshold|vma|sortie longue|long run|trail|velo|bike|cycling|home trainer|zwift|spinning|assault bike|air bike|echo bike|rameur|rower|rowing machine|erg|ski erg|skierg|natation|nage|swim|swimming|crawl|brasse|elliptique|elliptical|marche|walk|randonnee|hike|escaliers|stairs|stepper|corde a sauter|jump rope|double unders|double under|du|burpee|burpees|wall ball|wall balls|battle rope|mountain climber|mountain climbers|jumping jack|jumping jacks|cardio|zone 2|z2|intervalle|allure|marathon|semi marathon|fartlek|vo2|pma|travail continu|sortie|sortie endurance|ftp|piscine|airbike|velo doux|circuit|hiit|benchmark wod|fran|grace|murph|cindy|helen|chipper|conditioning|anaerobie|lactique|puissance anaerobie`,
  skill: `sparring|shadow|shadow boxing|punch bag|sac de frappe|pao|assaut|combinaison|combination|technique de base|geste fondamental|gestes fondamentaux|jeu reduit|jeux reduits|jeu|jeux|effectif reduit|match|opposition|tactique|transition|pressing|passe|tir|shoot|dribble|escalade|bloc|voie|grimpe|pan|poutre|hangboard|suspension|parcours|obstacle|franchissement|randori|uchi komi|kata|frappe|service|smash|technique|bloc principal technique|prehension|reglette|bac|virage|virages|skill|skills|gymnastics|kipping`,
  test: `test|yo yo|yoyo|yo yo test|luc leger|vameval|cooper|test de cooper|detente|detente verticale|test de detente|chrono|chronometre|1rm|illinois|t test|max test|evaluation|mensuration|tour de taille|trace barre|benchmark`,
  warm: `echauffement|warm up|warmup|activation|mobilite|mobility|etirement|etirements|stretching|stretch|retour au calme|cool down|cooldown|foam roller|foam roll|rouleau|yoga|respiration|breathing|prehab|prehabilitation|routine|elastique|band|circuit elastic activation|tech warmup|foam rolling|recuperation|recuperation active|recup active|prevention|prevention blessure|routine mobilite|mobilite epaules|echauffement articulaire|coiffe des rotateurs|rotateur|scapulaire|renforcement scapulaire|balneo|cryotherapie|bain froid|sauna`,
};

export const CATEGORY_LABEL: Record<ExerciseCategory, string> = { halt: "Haltéro", legs: "Jambes", push: "Poussée", pull: "Tirage", plio: "Pliométrie", sprint: "Sprint", core: "Gainage", cardio: "Cardio", warm: "Échauffement / prévention", skill: "Technique / sport", test: "Test" };
/** Famille de couleur : force, explosivité, autre. */
export const CATEGORY_FAMILY: Record<ExerciseCategory, "f" | "e" | "o"> = { halt: "f", legs: "f", push: "f", pull: "f", plio: "e", sprint: "e", core: "o", cardio: "o", warm: "o", skill: "e", test: "o" };

const norm = (s: string) => " " + s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9&]+/g, " ").trim()
  .split(" ").map(w => w.length > 3 && /[sx]$/.test(w) && !/ss$/.test(w) ? w.slice(0, -1) : w).join(" ") + " ";
const TERMS: { cat: ExerciseCategory; key: string }[] = [];
for (const cat of Object.keys(BANK) as ExerciseCategory[]) for (const t of BANK[cat].split("|")) TERMS.push({ cat, key: norm(t) });
const JUMPY = /\b(jump|saut|saute|sautee|hop|bound|bounding|switch|plio|pogo)\b/;

export function bestExerciseMatch(text: string): { cat: ExerciseCategory; key: string } | null {
  const n = norm(text);
  let best: { cat: ExerciseCategory; key: string; at: number } | null = null;
  for (const x of TERMS) {
    const at = n.indexOf(x.key);
    if (at < 0) continue;
    if (!best || x.key.length > best.key.length || (x.key.length === best.key.length && at < best.at)) best = { ...x, at };
  }
  if (best && best.cat === "legs" && JUMPY.test(n)) return { cat: "plio", key: best.key }; // "split squat jump"
  return best ? { cat: best.cat, key: best.key } : null;
}
